# Generated by Django 5.1.3 on 2024-11-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_language_book_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
    ]
